/*
 * Fifty recipes for a development database.
 *
 * Written to exercise every optional field rather than to look tidy: some
 * recipes carry a full nutrient table and some carry none, some have a calorie
 * figure and some leave it unknown, allergen lists run from empty to six
 * entries, and a few use the free-text allergen slot the picker offers. That
 * spread is the point — a seed where every record is complete tells you nothing
 * about how the app looks when a cook only filled in half the form.
 *
 * No images. They are meant to be added once there is somewhere to put them.
 *
 * The video links are real, and the seeder checks every one of them against
 * YouTube before writing: anything that no longer resolves is dropped and the
 * recipe is stored without a video. A link that looks right and plays nothing
 * is worse than no link, and inventing plausible-looking video ids is the
 * easiest way to produce exactly that.
 *
 * `time` is in minutes; everything nutritional is per serving.
 */

module.exports = [
    {
        title: 'Chicken Karahi',
        time: 45,
        servings: 4,
        mealTypes: ['lunch', 'dinner'],
        regions: ['south-asian'],
        countries: ['Pakistan'],
        allergens: ['dairy'],
        diets: ['halal', 'gluten-free', 'nut-free', 'egg-free', 'low-carb'],
        calories: 520,
        nutrients: [
            { name: 'protein', amount: 42, unit: 'g' },
            { name: 'fat', amount: 34, unit: 'g' },
            { name: 'carbohydrates', amount: 12, unit: 'g' },
            { name: 'sodium', amount: 780, unit: 'mg' },
            { name: 'iron', amount: 3.1, unit: 'mg' },
        ],
        videoUrl: 'https://www.youtube.com/watch?v=VKBiWOi4qvQ',
        ingredients: [
            '900 g bone-in chicken, cut small',
            '4 tbsp ghee',
            '500 g tomatoes, roughly chopped',
            '2 tbsp ginger, julienned',
            '6 green chillies, slit',
            '1 tbsp crushed coriander seed',
            '2 tbsp cream',
            'Salt',
        ],
        instructions: [
            'Heat the ghee in a wok until it shimmers, then fry the chicken hard until the pieces take colour on every side.',
            'Add the tomatoes and salt, cover, and cook until they collapse and the oil separates out — about 15 minutes.',
            'Stir in the crushed coriander and half the chillies, and fry uncovered until the sauce clings to the meat.',
            'Finish with the cream, the ginger and the rest of the chillies. Do not stir it smooth; karahi should stay ragged.',
        ],
    },
    {
        title: 'Spaghetti Carbonara',
        time: 25,
        servings: 2,
        mealTypes: ['lunch', 'dinner'],
        regions: ['mediterranean', 'western-european'],
        countries: ['Italy'],
        allergens: ['gluten', 'eggs', 'dairy'],
        diets: ['nut-free'],
        calories: 780,
        nutrients: [
            { name: 'protein', amount: 34, unit: 'g' },
            { name: 'carbohydrates', amount: 82, unit: 'g' },
            { name: 'fat', amount: 32, unit: 'g' },
            { name: 'saturated-fat', amount: 13, unit: 'g' },
            { name: 'sodium', amount: 920, unit: 'mg' },
        ],
        videoUrl: 'https://www.youtube.com/watch?v=AvO8UPbIH30',
        ingredients: [
            '200 g spaghetti',
            '100 g guanciale, cut into batons',
            '2 whole eggs plus 2 yolks',
            '60 g pecorino romano, finely grated',
            'Black pepper, coarsely ground',
        ],
        instructions: [
            'Render the guanciale slowly in a cold dry pan until the fat runs clear and the edges crisp.',
            'Beat the eggs with the pecorino and a great deal of black pepper.',
            'Cook the spaghetti in well-salted water, reserving a mugful before draining.',
            'Off the heat, toss the pasta through the guanciale fat, then the egg mixture, loosening with pasta water until it turns glossy.',
            'Serve at once. The heat of the pan does the cooking — put it back on the flame and you have made scrambled egg.',
        ],
    },
    {
        title: 'Shakshuka',
        time: 30,
        servings: 2,
        mealTypes: ['breakfast', 'brunch'],
        regions: ['levantine', 'north-african'],
        countries: ['Israel', 'Tunisia'],
        allergens: ['eggs'],
        diets: ['vegetarian', 'gluten-free', 'dairy-free', 'nut-free', 'halal', 'kosher', 'low-carb'],
        calories: 310,
        nutrients: [
            { name: 'protein', amount: 18, unit: 'g' },
            { name: 'carbohydrates', amount: 16, unit: 'g' },
            { name: 'fat', amount: 20, unit: 'g' },
            { name: 'fibre', amount: 5, unit: 'g' },
            { name: 'vitamin-c', amount: 88, unit: 'mg' },
        ],
        videoUrl: 'https://www.youtube.com/watch?v=m5Kn9WmOCrw',
        ingredients: [
            '2 tbsp olive oil',
            '1 onion, sliced',
            '2 red peppers, sliced',
            '3 cloves garlic',
            '1 tsp cumin seed',
            '1 tsp sweet paprika',
            '400 g tin plum tomatoes',
            '4 eggs',
            'Parsley, to finish',
        ],
        instructions: [
            'Soften the onion and peppers in the oil over a low heat for a good ten minutes — they should sweeten, not colour.',
            'Add the garlic and spices and fry for a minute until fragrant.',
            'Tip in the tomatoes, crush them against the pan, and simmer until thick enough to hold a channel behind a spoon.',
            'Make four wells, break an egg into each, cover, and cook until the whites set and the yolks still run.',
            'Scatter with parsley and take the pan to the table.',
        ],
    },
    {
        title: 'Pad Thai',
        time: 35,
        servings: 2,
        mealTypes: ['lunch', 'dinner'],
        regions: ['southeast-asian'],
        countries: ['Thailand'],
        allergens: ['peanuts', 'eggs', 'fish', 'shellfish', 'soy'],
        diets: ['dairy-free'],
        calories: 640,
        nutrients: [
            { name: 'protein', amount: 28, unit: 'g' },
            { name: 'carbohydrates', amount: 74, unit: 'g' },
            { name: 'fat', amount: 24, unit: 'g' },
            { name: 'sugars', amount: 16, unit: 'g' },
            { name: 'sodium', amount: 1450, unit: 'mg' },
        ],
        videoUrl: 'https://www.youtube.com/watch?v=kBBnBF3sOws',
        ingredients: [
            '200 g flat rice noodles, soaked',
            '150 g prawns',
            '2 eggs',
            '3 tbsp tamarind paste',
            '2 tbsp palm sugar',
            '2 tbsp fish sauce',
            '2 tbsp dried shrimp',
            '100 g beansprouts',
            '4 tbsp roasted peanuts, crushed',
            '2 spring onions',
        ],
        instructions: [
            'Melt the palm sugar into the tamarind and fish sauce over a low heat and set the sauce aside.',
            'Get a wok very hot. Fry the prawns and dried shrimp for a minute, then push them to one side.',
            'Break in the eggs, scramble them roughly, then add the drained noodles and the sauce.',
            'Toss hard until the noodles have taken up the sauce and started to catch in places.',
            'Fold through the beansprouts and spring onions, and finish with the crushed peanuts.',
        ],
    },
    {
        title: 'Jollof Rice',
        time: 60,
        servings: 6,
        mealTypes: ['lunch', 'dinner'],
        regions: ['west-african'],
        countries: ['Nigeria'],
        allergens: [],
        diets: ['vegan', 'vegetarian', 'gluten-free', 'dairy-free', 'egg-free', 'nut-free', 'halal', 'kosher'],
        calories: 430,
        nutrients: [
            { name: 'carbohydrates', amount: 78, unit: 'g' },
            { name: 'protein', amount: 8, unit: 'g' },
            { name: 'fat', amount: 10, unit: 'g' },
            { name: 'sodium', amount: 640, unit: 'mg' },
        ],
        videoUrl: 'https://www.youtube.com/watch?v=CxzQee6HZx8',
        ingredients: [
            '500 g long-grain parboiled rice',
            '6 plum tomatoes',
            '2 red peppers',
            '1 scotch bonnet',
            '2 onions',
            '4 tbsp tomato purée',
            '120 ml groundnut oil',
            '2 bay leaves',
            '1 tsp thyme',
            '700 ml vegetable stock',
        ],
        instructions: [
            'Blend the tomatoes, peppers, scotch bonnet and one onion to a smooth purée.',
            'Slice the second onion and soften it in the oil, then fry the tomato purée until it darkens.',
            'Pour in the blended peppers and cook down hard, twenty minutes or more, until the raw edge is gone and the oil floats.',
            'Stir in the rice, stock, bay and thyme. Cover with foil and a lid, and cook on the lowest heat for 30 minutes without lifting it.',
            'Let it catch very slightly at the base at the end — that faint smoke is the whole point.',
        ],
    },
    {
        title: 'Tacos al Pastor',
        time: 240,
        servings: 6,
        mealTypes: ['lunch', 'dinner'],
        regions: ['latin-american'],
        countries: ['Mexico'],
        allergens: [],
        diets: ['gluten-free', 'dairy-free', 'egg-free', 'nut-free'],
        calories: 480,
        nutrients: [
            { name: 'protein', amount: 32, unit: 'g' },
            { name: 'fat', amount: 26, unit: 'g' },
            { name: 'carbohydrates', amount: 30, unit: 'g' },
        ],
        videoUrl: 'https://www.youtube.com/watch?v=mwrFx2DdmO0',
        ingredients: [
            '1.2 kg pork shoulder, sliced thin',
            '4 guajillo chillies',
            '2 ancho chillies',
            '3 tbsp achiote paste',
            '120 ml pineapple juice',
            '3 tbsp white vinegar',
            '1 pineapple, sliced',
            'Corn tortillas',
            'White onion and coriander, to serve',
        ],
        instructions: [
            'Toast the chillies briefly, soak them in hot water for twenty minutes, then blend with the achiote, pineapple juice and vinegar.',
            'Coat the pork in the marinade and leave it in the fridge for at least three hours, overnight if you can.',
            'Stack the slices on a skewer with pineapple between them, or lay them flat on a very hot griddle.',
            'Cook until the edges char, then slice off thin shavings.',
            'Warm the tortillas, pile on the pork, and top with onion, coriander and a little grilled pineapple.',
        ],
    },
    {
        title: 'Hummus',
        time: 15,
        servings: 6,
        mealTypes: ['appetizer', 'side', 'snack'],
        regions: ['levantine', 'middle-eastern'],
        countries: ['Lebanon'],
        allergens: ['sesame'],
        diets: ['vegan', 'vegetarian', 'gluten-free', 'dairy-free', 'egg-free', 'nut-free', 'halal', 'kosher'],
        calories: 180,
        nutrients: [
            { name: 'protein', amount: 6, unit: 'g' },
            { name: 'fat', amount: 12, unit: 'g' },
            { name: 'carbohydrates', amount: 14, unit: 'g' },
            { name: 'fibre', amount: 4, unit: 'g' },
            { name: 'iron', amount: 1.8, unit: 'mg' },
        ],
        videoUrl: 'https://www.youtube.com/watch?v=gnVbLvqqDe8',
        ingredients: [
            '250 g dried chickpeas, soaked overnight',
            '1 tsp bicarbonate of soda',
            '150 g tahini',
            '2 lemons, juiced',
            '2 cloves garlic',
            'Ice water',
            'Salt and olive oil',
        ],
        instructions: [
            'Boil the drained chickpeas with the bicarbonate of soda until they are falling apart — further than seems sensible.',
            'Blend them hot with the tahini, lemon juice, garlic and salt.',
            'Trickle in ice water with the motor running until the texture turns pale and almost pourable.',
            'Spread into a bowl, pull a channel through it with the back of a spoon, and flood it with olive oil.',
        ],
    },
    {
        title: 'Tonkotsu Ramen',
        time: 720,
        servings: 4,
        mealTypes: ['dinner'],
        regions: ['east-asian'],
        countries: ['Japan'],
        allergens: ['gluten', 'eggs', 'soy'],
        diets: [],
        calories: 850,
        nutrients: [
            { name: 'protein', amount: 46, unit: 'g' },
            { name: 'carbohydrates', amount: 78, unit: 'g' },
            { name: 'fat', amount: 38, unit: 'g' },
            { name: 'sodium', amount: 2100, unit: 'mg' },
        ],
        videoUrl: 'https://www.youtube.com/watch?v=lyVINyzHh9M',
        ingredients: [
            '2 kg pork trotters and neck bones',
            '500 g pork belly, rolled',
            '4 portions fresh ramen noodles',
            '4 eggs',
            '100 ml soy sauce',
            '50 ml mirin',
            '1 head garlic',
            'Spring onion and nori, to serve',
        ],
        instructions: [
            'Blanch the bones for ten minutes, scrub them clean, then boil hard in fresh water for at least ten hours, topping up as it reduces.',
            'Braise the pork belly in soy sauce and mirin until a skewer slides through, then chill it and slice it thin.',
            'Marinate soft-boiled eggs in the cooled braising liquid for a few hours.',
            'Cook the noodles for the time on the packet and not a second longer.',
            'Build each bowl with tare in the base, broth over, then noodles, pork, egg, spring onion and nori.',
        ],
    },
    {
        title: 'Chicken Biryani',
        time: 90,
        servings: 6,
        mealTypes: ['lunch', 'dinner'],
        regions: ['south-asian'],
        countries: ['Pakistan', 'India'],
        allergens: ['dairy', 'tree-nuts'],
        diets: ['halal', 'egg-free'],
        calories: 610,
        nutrients: [
            { name: 'protein', amount: 34, unit: 'g' },
            { name: 'carbohydrates', amount: 68, unit: 'g' },
            { name: 'fat', amount: 22, unit: 'g' },
            { name: 'sodium', amount: 890, unit: 'mg' },
            { name: 'calcium', amount: 120, unit: 'mg' },
        ],
        videoUrl: 'https://www.youtube.com/watch?v=psjfRM4m2Rk',
        ingredients: [
            '1 kg chicken, jointed',
            '600 g basmati rice',
            '300 g yoghurt',
            '3 onions, sliced and fried crisp',
            '2 tbsp ginger-garlic paste',
            '2 tsp garam masala',
            'Large pinch saffron in warm milk',
            'Handful cashews',
            'Mint and coriander',
        ],
        instructions: [
            'Marinate the chicken in yoghurt, ginger-garlic, garam masala and half the fried onions for an hour.',
            'Parboil the soaked rice in heavily salted water with whole spices until it is done about seventy per cent.',
            'Layer the marinated chicken in a heavy pot, then the rice, then the remaining onions, herbs, cashews and saffron milk.',
            'Seal the lid with foil or dough and cook on the lowest possible heat for 40 minutes.',
            'Leave it sealed for another ten minutes off the heat, then open it at the table and fold the layers together once.',
        ],
    },
    {
        title: 'Phở Bò',
        time: 300,
        servings: 6,
        mealTypes: ['breakfast', 'lunch', 'dinner'],
        regions: ['southeast-asian'],
        countries: ['Vietnam'],
        allergens: ['fish', 'soy'],
        diets: ['dairy-free', 'egg-free', 'nut-free'],
        calories: 450,
        nutrients: [
            { name: 'protein', amount: 30, unit: 'g' },
            { name: 'carbohydrates', amount: 52, unit: 'g' },
            { name: 'fat', amount: 12, unit: 'g' },
            { name: 'sodium', amount: 1600, unit: 'mg' },
        ],
        videoUrl: 'https://www.youtube.com/watch?v=5bIjDYEs6Qc&t=1m30s',
        ingredients: [
            '2 kg beef bones, marrow and knuckle',
            '500 g brisket',
            '300 g beef fillet, sliced paper-thin',
            '1 onion and 1 large piece ginger, charred',
            '4 star anise, 1 cinnamon stick, 4 cloves',
            '3 tbsp fish sauce',
            '600 g fresh rice noodles',
            'Thai basil, beansprouts, lime and chilli',
        ],
        instructions: [
            'Parboil the bones for fifteen minutes and rinse every trace of scum away — this is what makes the broth clear.',
            'Char the onion and ginger over a flame until blackened in patches.',
            'Simmer bones, brisket, charred aromatics and toasted spices for four hours, skimming and never letting it boil.',
            'Season with fish sauce and a little rock sugar. Slice the cooked brisket.',
            'Put noodles in each bowl, lay the raw fillet over, and ladle broth on hard enough to cook it through. Herbs go on at the table.',
        ],
    },
    {
        title: 'Paella Valenciana',
        time: 75,
        servings: 6,
        mealTypes: ['lunch', 'dinner'],
        regions: ['mediterranean', 'western-european'],
        countries: ['Spain'],
        allergens: [],
        diets: ['gluten-free', 'dairy-free', 'egg-free', 'nut-free'],
        calories: 560,
        nutrients: [
            { name: 'protein', amount: 36, unit: 'g' },
            { name: 'carbohydrates', amount: 62, unit: 'g' },
            { name: 'fat', amount: 18, unit: 'g' },
        ],
        videoUrl: 'https://www.youtube.com/watch?v=9VpltI6VjiA',
        ingredients: [
            '500 g chicken, jointed small',
            '400 g rabbit, jointed small',
            '200 g flat green beans',
            '150 g butter beans',
            '400 g bomba rice',
            '2 grated tomatoes',
            'Generous pinch saffron',
            '1 tsp sweet paprika',
            '1.2 litres water',
        ],
        instructions: [
            'Brown the chicken and rabbit slowly in olive oil in the pan you will serve from, pushing them out to the rim as they colour.',
            'Fry the beans, then the grated tomato and paprika, until the mixture darkens.',
            'Add the water and saffron and simmer for half an hour to build the stock in the pan.',
            'Scatter the rice evenly across and do not stir it again. Cook hard for ten minutes, then gently for eight.',
            'Turn the heat up for a final minute to set the socarrat underneath, then rest it for five before serving.',
        ],
    },
    {
        title: 'Tiramisù',
        time: 40,
        servings: 8,
        mealTypes: ['dessert'],
        regions: ['mediterranean', 'western-european'],
        countries: ['Italy'],
        allergens: ['eggs', 'dairy', 'gluten'],
        diets: ['vegetarian', 'nut-free'],
        calories: 420,
        nutrients: [
            { name: 'fat', amount: 28, unit: 'g' },
            { name: 'carbohydrates', amount: 32, unit: 'g' },
            { name: 'protein', amount: 8, unit: 'g' },
            { name: 'sugars', amount: 24, unit: 'g' },
        ],
        videoUrl: 'https://www.youtube.com/watch?v=cj3iwfB0DVA',
        ingredients: [
            '4 egg yolks',
            '100 g caster sugar',
            '500 g mascarpone',
            '300 ml strong espresso, cooled',
            '2 tbsp marsala',
            '30 savoiardi biscuits',
            'Cocoa powder',
        ],
        instructions: [
            'Whisk the yolks and sugar over a pan of barely simmering water until thick and pale, then take it off and cool it.',
            'Beat in the mascarpone a spoonful at a time so it stays smooth.',
            'Mix the marsala into the coffee. Dip each biscuit for one second only — any longer and the whole thing collapses.',
            'Layer biscuits and cream twice, finishing with cream.',
            'Chill for at least six hours, and dust with cocoa only as it goes to the table.',
        ],
    },
    {
        title: 'Falafel',
        time: 40,
        servings: 4,
        mealTypes: ['lunch', 'snack', 'appetizer'],
        regions: ['middle-eastern', 'levantine'],
        countries: ['Egypt', 'Lebanon'],
        allergens: ['sesame'],
        diets: ['vegan', 'vegetarian', 'dairy-free', 'egg-free', 'nut-free', 'halal', 'kosher'],
        calories: 330,
        nutrients: [
            { name: 'protein', amount: 13, unit: 'g' },
            { name: 'carbohydrates', amount: 30, unit: 'g' },
            { name: 'fat', amount: 18, unit: 'g' },
            { name: 'fibre', amount: 8, unit: 'g' },
            { name: 'folate', amount: 210, unit: 'µg' },
        ],
        videoUrl: 'https://www.youtube.com/watch?v=aQD0ndQGpG0',
        ingredients: [
            '250 g dried chickpeas, soaked 24 hours',
            '1 onion',
            '4 cloves garlic',
            'Large bunch parsley',
            'Large bunch coriander',
            '1 tsp cumin, 1 tsp coriander seed',
            '1 tsp bicarbonate of soda',
            'Oil for frying',
        ],
        instructions: [
            'Never boil the chickpeas. Soaked and raw is the whole recipe — cooked ones turn to paste and fall apart in the oil.',
            'Blitz everything except the bicarbonate to a coarse, damp crumb, stopping before it becomes a purée.',
            'Chill for an hour, then stir the bicarbonate through just before frying.',
            'Shape into small patties and fry at 175°C until deep brown, about four minutes.',
            'Drain and eat straight away with tahini sauce.',
        ],
    },
    {
        title: 'Jerk Chicken',
        time: 180,
        servings: 4,
        mealTypes: ['lunch', 'dinner'],
        regions: ['caribbean'],
        countries: ['Jamaica'],
        allergens: [],
        diets: ['gluten-free', 'dairy-free', 'egg-free', 'nut-free', 'halal'],
        calories: 490,
        nutrients: [
            { name: 'protein', amount: 44, unit: 'g' },
            { name: 'fat', amount: 30, unit: 'g' },
            { name: 'carbohydrates', amount: 8, unit: 'g' },
            { name: 'sodium', amount: 980, unit: 'mg' },
        ],
        videoUrl: 'https://www.youtube.com/watch?v=i0B1lT72PrM',
        ingredients: [
            '1.5 kg chicken thighs and drumsticks',
            '4 scotch bonnets',
            '6 spring onions',
            '2 tbsp fresh thyme',
            '2 tbsp ground allspice',
            '4 cloves garlic',
            '3 tbsp soy sauce',
            '2 tbsp brown sugar',
            '1 lime',
        ],
        instructions: [
            'Blend everything but the chicken into a thick, dark paste.',
            'Score the chicken to the bone and work the marinade in. Leave it overnight if you have the time.',
            'Cook slowly over indirect heat — coals to one side, chicken to the other — for about an hour.',
            'Add pimento wood or soaked chips if you have them, and keep the lid down.',
            'Finish directly over the coals for colour, and chop into pieces to serve.',
        ],
    },
    {
        title: 'Bibimbap',
        time: 45,
        servings: 2,
        mealTypes: ['lunch', 'dinner'],
        regions: ['east-asian'],
        countries: ['South Korea'],
        allergens: ['eggs', 'soy', 'sesame'],
        diets: ['dairy-free', 'nut-free'],
        calories: 590,
        nutrients: [
            { name: 'protein', amount: 26, unit: 'g' },
            { name: 'carbohydrates', amount: 76, unit: 'g' },
            { name: 'fat', amount: 20, unit: 'g' },
            { name: 'fibre', amount: 7, unit: 'g' },
        ],
        videoUrl: 'https://www.youtube.com/watch?v=6QQ67F8y2b8&list=PLseedexample',
        ingredients: [
            '300 g short-grain rice, cooked',
            '150 g beef mince',
            '100 g spinach',
            '100 g beansprouts',
            '1 carrot, julienned',
            '4 shiitake mushrooms',
            '2 eggs',
            '3 tbsp gochujang',
            'Sesame oil and toasted sesame seeds',
        ],
        instructions: [
            'Season each vegetable separately — blanched spinach with sesame oil and garlic, beansprouts likewise, carrot and mushroom fried apart.',
            'Fry the beef with soy, garlic and a little sugar until glossy.',
            'Press the rice into a hot stone bowl if you have one, so a crust forms underneath.',
            'Arrange everything in wedges over the rice and set a fried egg in the middle.',
            'Add gochujang at the table and mix the whole thing thoroughly before eating.',
        ],
    },
    {
        title: 'Chicken Tagine with Preserved Lemon',
        time: 90,
        servings: 4,
        mealTypes: ['dinner'],
        regions: ['north-african'],
        countries: ['Morocco'],
        allergens: [],
        diets: ['halal', 'gluten-free', 'dairy-free', 'egg-free', 'nut-free'],
        calories: 470,
        nutrients: [
            { name: 'protein', amount: 40, unit: 'g' },
            { name: 'fat', amount: 26, unit: 'g' },
            { name: 'carbohydrates', amount: 14, unit: 'g' },
            { name: 'sodium', amount: 1100, unit: 'mg' },
        ],
        videoUrl: 'https://www.youtube.com/watch?v=Wqc_LbRrMRI',
        ingredients: [
            '1.4 kg chicken, jointed',
            '2 preserved lemons',
            '150 g green olives',
            '2 onions, sliced',
            '1 tsp ginger, 1 tsp turmeric',
            'Pinch saffron',
            'Large bunch coriander and parsley',
            '3 tbsp olive oil',
        ],
        instructions: [
            'Rub the chicken with the spices, garlic and half the chopped herbs and leave it for an hour.',
            'Lay the onions in the base of a tagine or heavy casserole and set the chicken on top.',
            'Add a splash of water, cover, and cook very gently for an hour — it should barely murmur.',
            'Add the olives and the preserved lemon, cut into quarters, for the last fifteen minutes.',
            'Reduce the sauce if it is loose, and scatter the rest of the herbs over before serving.',
        ],
    },
    {
        title: 'Buttermilk Pancakes',
        time: 25,
        servings: 4,
        mealTypes: ['breakfast', 'brunch'],
        regions: ['north-american'],
        countries: ['United States'],
        allergens: ['gluten', 'dairy', 'eggs'],
        diets: ['vegetarian', 'nut-free'],
        calories: 380,
        nutrients: [
            { name: 'carbohydrates', amount: 52, unit: 'g' },
            { name: 'protein', amount: 11, unit: 'g' },
            { name: 'fat', amount: 14, unit: 'g' },
            { name: 'sugars', amount: 12, unit: 'g' },
            { name: 'calcium', amount: 180, unit: 'mg' },
        ],
        videoUrl: 'https://www.youtube.com/watch?v=R2C5GUDLqb0',
        ingredients: [
            '250 g plain flour',
            '2 tbsp caster sugar',
            '2 tsp baking powder',
            '1 tsp bicarbonate of soda',
            '400 ml buttermilk',
            '2 eggs',
            '50 g butter, melted',
            'Pinch salt',
        ],
        instructions: [
            'Whisk the dry ingredients together in one bowl and the wet in another.',
            'Combine them with about ten strokes. Lumps are correct; a smooth batter makes flat, tough pancakes.',
            'Rest the batter for ten minutes while the pan heats to medium.',
            'Cook until bubbles break across the surface and the edges look dry, then turn once.',
        ],
    },
    {
        title: 'Butter Chicken',
        time: 60,
        servings: 4,
        mealTypes: ['dinner'],
        regions: ['south-asian'],
        countries: ['India'],
        allergens: ['dairy', 'tree-nuts'],
        diets: ['halal', 'gluten-free', 'egg-free'],
        calories: 640,
        nutrients: [
            { name: 'protein', amount: 38, unit: 'g' },
            { name: 'fat', amount: 44, unit: 'g' },
            { name: 'carbohydrates', amount: 18, unit: 'g' },
            { name: 'saturated-fat', amount: 22, unit: 'g' },
        ],
        videoUrl: 'https://www.youtube.com/watch?v=ZkvbDB0cgMk',
        ingredients: [
            '800 g chicken thigh',
            '200 g yoghurt',
            '2 tbsp ginger-garlic paste',
            '2 tsp kashmiri chilli powder',
            '400 g tomato purée',
            '80 g butter',
            '150 ml double cream',
            '50 g cashews, soaked',
            '1 tsp kasuri methi',
        ],
        instructions: [
            'Marinate the chicken in yoghurt, ginger-garlic and chilli for at least four hours.',
            'Grill or char the pieces hard until they blacken at the edges but stay underdone in the middle.',
            'Simmer the tomato purée with the soaked cashews for twenty minutes, then blend it smooth and pass it through a sieve.',
            'Melt in the butter and cream, return the chicken, and finish cooking it through in the sauce.',
            'Crush the kasuri methi between your palms over the pan at the very end.',
        ],
    },
    {
        title: 'Guacamole',
        time: 10,
        servings: 4,
        mealTypes: ['appetizer', 'snack', 'side'],
        regions: ['latin-american'],
        countries: ['Mexico'],
        allergens: [],
        diets: ['vegan', 'vegetarian', 'gluten-free', 'dairy-free', 'egg-free', 'nut-free', 'halal', 'kosher', 'low-carb', 'paleo'],
        calories: 160,
        nutrients: [
            { name: 'fat', amount: 14, unit: 'g' },
            { name: 'fibre', amount: 6, unit: 'g' },
            { name: 'carbohydrates', amount: 8, unit: 'g' },
            { name: 'potassium', amount: 480, unit: 'mg' },
            { name: 'vitamin-e', amount: 2.1, unit: 'mg' },
        ],
        videoUrl: 'https://youtu.be/a6yCQdx3Pkg',
        ingredients: [
            '3 ripe Hass avocados',
            '1 small white onion, finely diced',
            '2 serrano chillies, finely chopped',
            'Small bunch coriander',
            '1 lime',
            'Salt',
        ],
        instructions: [
            'Grind the onion, chilli, coriander stalks and salt to a rough paste — a molcajete if you have one, the side of a knife if not.',
            'Add the avocado and mash it against the paste, leaving it lumpy.',
            'Fold in the chopped coriander leaves and lime juice, and taste for salt twice.',
            'Make it as close to eating as you can manage.',
        ],
    },
    {
        title: 'Mapo Tofu',
        time: 30,
        servings: 3,
        mealTypes: ['lunch', 'dinner'],
        regions: ['east-asian'],
        countries: ['China'],
        allergens: ['soy'],
        diets: ['dairy-free', 'egg-free', 'nut-free'],
        calories: 380,
        nutrients: [
            { name: 'protein', amount: 24, unit: 'g' },
            { name: 'fat', amount: 26, unit: 'g' },
            { name: 'carbohydrates', amount: 12, unit: 'g' },
            { name: 'sodium', amount: 1350, unit: 'mg' },
            { name: 'calcium', amount: 320, unit: 'mg' },
        ],
        videoUrl: 'https://www.youtube.com/watch?v=IZOs9hr3ISk',
        ingredients: [
            '500 g silken tofu, cubed',
            '150 g pork mince',
            '2 tbsp doubanjiang',
            '1 tbsp douchi, rinsed',
            '1 tbsp ground Sichuan pepper',
            '300 ml chicken stock',
            '2 tsp cornflour',
            'Garlic sprouts or spring onion',
        ],
        instructions: [
            'Slip the tofu into salted water just under the boil and leave it there while you cook everything else.',
            'Fry the pork until it is dry and crisp, then add the doubanjiang and cook until the oil turns deep red.',
            'Add the douchi, garlic and stock, and let it come to a simmer.',
            'Drain the tofu and fold it in with the back of a ladle — never a spoon end-on, or it breaks up.',
            'Thicken with cornflour slurry in three stages, then finish with sprouts and a heavy dusting of Sichuan pepper.',
        ],
    },
    {
        title: 'Pistachio Baklava',
        time: 120,
        servings: 20,
        mealTypes: ['dessert', 'snack'],
        regions: ['middle-eastern'],
        countries: ['Turkey'],
        allergens: ['tree-nuts', 'gluten', 'dairy'],
        diets: ['vegetarian', 'egg-free', 'alcohol-free'],
        calories: 290,
        nutrients: [
            { name: 'sugars', amount: 22, unit: 'g' },
            { name: 'fat', amount: 18, unit: 'g' },
            { name: 'carbohydrates', amount: 28, unit: 'g' },
            { name: 'protein', amount: 4, unit: 'g' },
        ],
        videoUrl: 'https://www.youtube.com/watch?v=JSh6Eg0Wxg4',
        ingredients: [
            '400 g filo pastry',
            '400 g pistachios, ground',
            '250 g clarified butter',
            '400 g sugar',
            '250 ml water',
            '1 tbsp lemon juice',
        ],
        instructions: [
            'Boil the sugar, water and lemon juice for fifteen minutes and cool the syrup completely.',
            'Butter each sheet of filo as you lay it down — half the sheets, then the pistachios, then the rest.',
            'Cut all the way through into diamonds before it goes anywhere near the oven.',
            'Bake at 170°C for about 45 minutes until evenly gold.',
            'Pour the cold syrup over the hot baklava. One of the two must be cold or it goes soggy.',
        ],
    },
    {
        title: 'Ceviche',
        time: 25,
        servings: 4,
        mealTypes: ['appetizer', 'lunch'],
        regions: ['latin-american'],
        countries: ['Peru'],
        allergens: ['fish'],
        diets: ['pescatarian', 'gluten-free', 'dairy-free', 'egg-free', 'nut-free', 'low-carb', 'paleo'],
        calories: 210,
        nutrients: [
            { name: 'protein', amount: 32, unit: 'g' },
            { name: 'carbohydrates', amount: 10, unit: 'g' },
            { name: 'fat', amount: 4, unit: 'g' },
            { name: 'vitamin-c', amount: 42, unit: 'mg' },
        ],
        videoUrl: 'https://www.youtube.com/watch?v=HbiAyZ2zogc',
        ingredients: [
            '600 g very fresh sea bass, cubed',
            '12 limes',
            '1 red onion, sliced paper-thin',
            '1 rocoto or habanero chilli',
            'Small bunch coriander',
            '1 clove garlic',
            'Sweet potato and corn, to serve',
        ],
        instructions: [
            'Squeeze the limes by hand and stop short of the pith — a juicer makes the whole dish bitter.',
            'Blend a little of the fish with lime, garlic, chilli and ice to make leche de tigre, then strain it.',
            'Rinse the sliced onion under cold water for a minute to take its edge off.',
            'Dress the fish in the leche de tigre for two minutes only. It should be opaque at the edge and raw at the centre.',
            'Serve immediately with cold sweet potato and boiled corn.',
        ],
    },
    {
        title: 'Chana Masala',
        time: 40,
        servings: 4,
        mealTypes: ['lunch', 'dinner'],
        regions: ['south-asian'],
        countries: ['India'],
        allergens: [],
        diets: ['vegan', 'vegetarian', 'gluten-free', 'dairy-free', 'egg-free', 'nut-free', 'halal', 'kosher'],
        calories: 340,
        nutrients: [
            { name: 'protein', amount: 14, unit: 'g' },
            { name: 'fibre', amount: 12, unit: 'g' },
            { name: 'carbohydrates', amount: 48, unit: 'g' },
            { name: 'iron', amount: 4.2, unit: 'mg' },
        ],
        ingredients: [
            '2 tins chickpeas, drained',
            '2 onions, finely chopped',
            '400 g tinned tomatoes',
            '1 tbsp ginger-garlic paste',
            '2 tsp ground cumin',
            '2 tsp ground coriander',
            '1 tsp amchur',
            '1 tsp garam masala',
        ],
        instructions: [
            'Fry the onions in oil until they are genuinely brown, not merely soft. This takes fifteen minutes and cannot be hurried.',
            'Add the ginger-garlic and ground spices and fry for a minute.',
            'Add the tomatoes and cook until the oil separates and pools at the edges.',
            'Stir in the chickpeas with a splash of water and simmer for fifteen minutes, crushing some against the pan to thicken it.',
            'Finish with amchur and garam masala off the heat.',
        ],
    },
    {
        title: 'Dal Tadka',
        time: 45,
        servings: 4,
        mealTypes: ['lunch', 'dinner', 'side'],
        regions: ['south-asian'],
        countries: ['India'],
        allergens: ['dairy'],
        diets: ['vegetarian', 'gluten-free', 'egg-free', 'nut-free', 'halal'],
        calories: 280,
        nutrients: [
            { name: 'protein', amount: 15, unit: 'g' },
            { name: 'carbohydrates', amount: 38, unit: 'g' },
            { name: 'fibre', amount: 9, unit: 'g' },
            { name: 'folate', amount: 180, unit: 'µg' },
        ],
        ingredients: [
            '250 g toor dal',
            '1 tsp turmeric',
            '3 tbsp ghee',
            '1 tsp cumin seed',
            '4 dried red chillies',
            '6 cloves garlic, sliced',
            '1 tomato, chopped',
            'Handful coriander',
        ],
        instructions: [
            'Boil the dal with turmeric and salt until it collapses entirely, then whisk it smooth.',
            'Heat the ghee until it is properly hot and add the cumin — it must crackle within a second or two.',
            'Add the garlic and chillies and take them just to golden, no further.',
            'Pour the tadka over the dal and put the lid on for a minute before stirring it through.',
        ],
    },
    {
        title: 'Aloo Paratha',
        time: 50,
        servings: 4,
        mealTypes: ['breakfast', 'brunch'],
        regions: ['south-asian'],
        countries: ['India', 'Pakistan'],
        allergens: ['gluten', 'dairy'],
        diets: ['vegetarian', 'egg-free', 'nut-free', 'halal'],
        calories: 390,
        nutrients: [
            { name: 'carbohydrates', amount: 56, unit: 'g' },
            { name: 'fat', amount: 14, unit: 'g' },
            { name: 'protein', amount: 9, unit: 'g' },
        ],
        ingredients: [
            '300 g atta flour',
            '4 potatoes, boiled and mashed',
            '2 green chillies, minced',
            '1 tsp ajwain',
            '1 tsp amchur',
            'Coriander, chopped',
            'Ghee for frying',
        ],
        instructions: [
            'Make a soft dough with the flour, water and a little oil, and rest it for twenty minutes.',
            'Mix the potato with the chilli, spices and coriander. Keep it dry — wet filling tears the dough every time.',
            'Roll a disc, mound the filling in the centre, gather the edges over it and seal, then roll out gently.',
            'Cook on a hot tawa, brushing both sides with ghee, until it is blistered and brown in patches.',
        ],
    },
    {
        title: 'Tabbouleh',
        time: 20,
        servings: 4,
        mealTypes: ['side', 'appetizer'],
        regions: ['levantine'],
        countries: ['Lebanon'],
        allergens: ['gluten'],
        diets: ['vegan', 'vegetarian', 'dairy-free', 'egg-free', 'nut-free', 'halal', 'kosher'],
        calories: 150,
        nutrients: [
            { name: 'carbohydrates', amount: 18, unit: 'g' },
            { name: 'fat', amount: 8, unit: 'g' },
            { name: 'vitamin-k', amount: 240, unit: 'µg' },
            { name: 'vitamin-c', amount: 60, unit: 'mg' },
        ],
        ingredients: [
            '4 large bunches flat parsley',
            '2 tbsp fine bulgur',
            '3 tomatoes, finely diced',
            '4 spring onions',
            'Small bunch mint',
            '1 lemon',
            '4 tbsp olive oil',
        ],
        instructions: [
            'Soak the bulgur in the juice of the tomatoes for ten minutes. It should barely swell.',
            'Chop the parsley by hand with a very sharp knife — a processor bruises it into a green sludge.',
            'Combine everything and dress it only when you are ready to eat.',
            'This is a herb salad with grain in it, not a grain salad with herbs. Keep the proportions that way round.',
        ],
    },
    {
        title: 'Chicken Shawarma',
        time: 150,
        servings: 4,
        mealTypes: ['lunch', 'dinner'],
        regions: ['levantine', 'middle-eastern'],
        countries: ['Lebanon', 'Syria'],
        allergens: ['dairy', 'sesame', 'gluten'],
        diets: ['halal', 'nut-free', 'egg-free'],
        calories: 520,
        nutrients: [
            { name: 'protein', amount: 42, unit: 'g' },
            { name: 'fat', amount: 24, unit: 'g' },
            { name: 'carbohydrates', amount: 34, unit: 'g' },
            { name: 'sodium', amount: 1020, unit: 'mg' },
        ],
        ingredients: [
            '900 g chicken thigh, sliced',
            '150 g yoghurt',
            '2 tbsp shawarma spice',
            '1 lemon',
            '4 cloves garlic',
            'Flatbreads',
            'Tahini sauce, pickles and tomato',
        ],
        instructions: [
            'Marinate the chicken in yoghurt, lemon, garlic and spice for at least two hours.',
            'Pack the slices tightly onto a skewer or press them into a single dense layer in a roasting tin.',
            'Roast hot at 220°C until the outside is dark and the inside still juicy.',
            'Rest, then shave off thin slices rather than cutting chunks.',
            'Fill warm flatbreads with chicken, tahini sauce, pickles and tomato.',
        ],
    },
    {
        title: 'Chicken Katsu Curry',
        time: 50,
        servings: 4,
        mealTypes: ['lunch', 'dinner'],
        regions: ['east-asian'],
        countries: ['Japan'],
        allergens: ['gluten', 'eggs', 'soy'],
        diets: ['dairy-free', 'nut-free'],
        calories: 720,
        nutrients: [
            { name: 'protein', amount: 40, unit: 'g' },
            { name: 'carbohydrates', amount: 84, unit: 'g' },
            { name: 'fat', amount: 26, unit: 'g' },
        ],
        ingredients: [
            '4 chicken breasts, butterflied',
            '150 g panko',
            '2 eggs',
            '100 g flour',
            '2 onions',
            '2 carrots',
            '3 tbsp curry powder',
            '1 tbsp garam masala',
            '600 ml chicken stock',
        ],
        instructions: [
            'Soften the onion and carrot slowly for twenty minutes, then stir in the curry powder and flour to make a roux.',
            'Add the stock gradually, simmer for fifteen minutes, and blend it smooth.',
            'Flour, egg and panko each chicken breast, pressing the crumbs on firmly.',
            'Fry at 170°C for four minutes a side until deep gold, then rest on a rack, never on paper.',
            'Slice across, and pour the sauce beside the katsu rather than over it.',
        ],
    },
    {
        title: 'Kimchi Jjigae',
        time: 40,
        servings: 3,
        mealTypes: ['lunch', 'dinner'],
        regions: ['east-asian'],
        countries: ['South Korea'],
        allergens: ['soy', 'fish', 'shellfish'],
        diets: ['dairy-free', 'egg-free', 'nut-free'],
        calories: 350,
        nutrients: [
            { name: 'protein', amount: 22, unit: 'g' },
            { name: 'fat', amount: 22, unit: 'g' },
            { name: 'sodium', amount: 1700, unit: 'mg' },
        ],
        ingredients: [
            '400 g very sour kimchi',
            '250 g pork belly, sliced',
            '300 g tofu',
            '1 tbsp gochugaru',
            '1 tbsp gochujang',
            '1 tsp saeujeot',
            '500 ml anchovy stock',
            '2 spring onions',
        ],
        instructions: [
            'Use the oldest kimchi you have. Fresh kimchi makes a thin, sweet stew with none of the depth.',
            'Fry the pork until the fat renders, then add the kimchi and its juice and fry for five minutes more.',
            'Stir in the gochugaru and gochujang, then pour in the stock.',
            'Simmer for twenty minutes, add the tofu in thick slices, and give it five minutes more.',
            'Scatter spring onion over and serve bubbling, with rice.',
        ],
    },
    {
        title: 'Thai Green Curry',
        time: 40,
        servings: 4,
        mealTypes: ['dinner'],
        regions: ['southeast-asian'],
        countries: ['Thailand'],
        allergens: ['fish', 'shellfish'],
        diets: ['gluten-free', 'dairy-free', 'egg-free', 'nut-free'],
        calories: 520,
        nutrients: [
            { name: 'fat', amount: 38, unit: 'g' },
            { name: 'protein', amount: 28, unit: 'g' },
            { name: 'carbohydrates', amount: 16, unit: 'g' },
            { name: 'saturated-fat', amount: 26, unit: 'g' },
        ],
        ingredients: [
            '600 g chicken thigh',
            '400 ml coconut milk',
            '4 tbsp green curry paste',
            '2 tbsp fish sauce',
            '1 tbsp palm sugar',
            '150 g pea aubergines',
            '4 kaffir lime leaves',
            'Thai basil',
        ],
        instructions: [
            'Crack the thick cream from the top of the coconut milk in a dry pan and fry the paste in it until the oil splits out.',
            'Add the chicken and turn it through the paste.',
            'Pour in the rest of the coconut milk, then the fish sauce and sugar.',
            'Simmer, do not boil, for fifteen minutes, adding the aubergines halfway.',
            'Tear in the lime leaves and basil at the end.',
        ],
    },
    {
        title: 'Nasi Goreng',
        time: 25,
        servings: 2,
        mealTypes: ['breakfast', 'lunch', 'dinner'],
        regions: ['southeast-asian'],
        countries: ['Indonesia'],
        allergens: ['eggs', 'soy', 'fish', 'shellfish'],
        diets: ['dairy-free', 'nut-free', 'halal'],
        calories: 480,
        ingredients: [
            '400 g cold cooked rice',
            '2 eggs',
            '3 shallots',
            '4 cloves garlic',
            '2 red chillies',
            '1 tsp terasi',
            '2 tbsp kecap manis',
            'Cucumber and prawn crackers, to serve',
        ],
        instructions: [
            'The rice must be cold and preferably a day old. Warm rice steams instead of frying and turns to paste.',
            'Pound the shallots, garlic, chilli and terasi to a paste and fry it in oil until fragrant.',
            'Add the rice and stir-fry over the highest heat you can manage, breaking up every clump.',
            'Stir the kecap manis through until the grains are evenly coloured.',
            'Top each plate with a fried egg and serve with cucumber and crackers.',
        ],
    },
    {
        title: 'Beef Rendang',
        time: 240,
        servings: 6,
        mealTypes: ['lunch', 'dinner'],
        regions: ['southeast-asian'],
        countries: ['Indonesia', 'Malaysia'],
        allergens: [],
        diets: ['halal', 'gluten-free', 'dairy-free', 'egg-free', 'nut-free'],
        calories: 610,
        nutrients: [
            { name: 'protein', amount: 44, unit: 'g' },
            { name: 'fat', amount: 42, unit: 'g' },
            { name: 'saturated-fat', amount: 28, unit: 'g' },
            { name: 'iron', amount: 5.1, unit: 'mg' },
        ],
        ingredients: [
            '1.2 kg beef shin, cubed',
            '800 ml coconut milk',
            '10 dried chillies',
            '6 shallots',
            '4 cloves garlic',
            'Thumb of galangal and turmeric',
            '3 lemongrass stalks, bruised',
            '6 kaffir lime leaves',
            '100 g toasted grated coconut',
        ],
        instructions: [
            'Blend the chillies, shallots, garlic, galangal and turmeric into a fine paste.',
            'Bring the coconut milk, paste, lemongrass and lime leaves to a simmer with the beef.',
            'Cook uncovered for three hours, stirring more often as it thickens.',
            'The liquid will break into oil and the whole thing will darken from pale to mahogany — that shift is the dish.',
            'Stir in the toasted coconut for the last twenty minutes, until it is dry enough to fry in its own oil.',
        ],
    },
    {
        title: 'Margherita Pizza',
        time: 1440,
        servings: 4,
        mealTypes: ['lunch', 'dinner'],
        regions: ['mediterranean', 'western-european'],
        countries: ['Italy'],
        allergens: ['gluten', 'dairy'],
        diets: ['vegetarian', 'egg-free', 'nut-free'],
        calories: 620,
        nutrients: [
            { name: 'carbohydrates', amount: 84, unit: 'g' },
            { name: 'protein', amount: 24, unit: 'g' },
            { name: 'fat', amount: 20, unit: 'g' },
            { name: 'calcium', amount: 340, unit: 'mg' },
        ],
        ingredients: [
            '500 g 00 flour',
            '325 ml water',
            '10 g salt',
            '1 g fresh yeast',
            '400 g San Marzano tomatoes',
            '250 g fiordilatte, torn and drained',
            'Basil and olive oil',
        ],
        instructions: [
            'Mix flour, water, salt and the very small amount of yeast, and knead until smooth.',
            'Leave it at room temperature for two hours, then refrigerate for 24. The long cold rise is what makes the crust taste of anything.',
            'Divide into balls four hours before baking and let them come back to room temperature.',
            'Stretch by hand from the centre out, leaving the rim untouched. Never use a rolling pin.',
            'Crush the tomatoes with salt only, top sparingly, and bake as hot as your oven goes on a preheated stone.',
        ],
    },
    {
        title: 'Risotto alla Milanese',
        time: 45,
        servings: 4,
        mealTypes: ['dinner', 'side'],
        regions: ['mediterranean', 'western-european'],
        countries: ['Italy'],
        allergens: ['dairy'],
        diets: ['vegetarian', 'gluten-free', 'egg-free', 'nut-free'],
        calories: 540,
        nutrients: [
            { name: 'carbohydrates', amount: 68, unit: 'g' },
            { name: 'fat', amount: 22, unit: 'g' },
            { name: 'protein', amount: 14, unit: 'g' },
        ],
        ingredients: [
            '320 g carnaroli rice',
            '1.2 litres vegetable stock, kept hot',
            '1 shallot, finely diced',
            '150 ml dry white wine',
            'Large pinch saffron threads',
            '80 g butter, very cold',
            '80 g parmesan',
        ],
        instructions: [
            'Soften the shallot in a little butter, then toast the rice until the grains turn translucent at the edges.',
            'Pour in the wine and let it evaporate completely.',
            'Add hot stock a ladle at a time, stirring, waiting each time until the pan is nearly dry.',
            'Bloom the saffron in a little stock and add it two-thirds of the way through.',
            'Off the heat, beat in the cold butter and parmesan hard until it ripples across the plate when shaken.',
        ],
    },
    {
        title: 'Ratatouille',
        time: 75,
        servings: 4,
        mealTypes: ['side', 'dinner'],
        regions: ['mediterranean', 'western-european'],
        countries: ['France'],
        allergens: [],
        diets: ['vegan', 'vegetarian', 'gluten-free', 'dairy-free', 'egg-free', 'nut-free', 'halal', 'kosher', 'low-carb', 'paleo'],
        calories: 190,
        nutrients: [
            { name: 'carbohydrates', amount: 18, unit: 'g' },
            { name: 'fibre', amount: 7, unit: 'g' },
            { name: 'fat', amount: 12, unit: 'g' },
            { name: 'vitamin-c', amount: 74, unit: 'mg' },
        ],
        ingredients: [
            '2 aubergines',
            '3 courgettes',
            '2 red peppers',
            '4 tomatoes',
            '2 onions',
            '4 cloves garlic',
            'Thyme and bay',
            'Good olive oil',
        ],
        instructions: [
            'Cook every vegetable separately in olive oil. This is the entire technique and there is no shortcut around it.',
            'Salt the aubergine first and let it drain for half an hour.',
            'Fry each one until browned and just tender, setting each aside as it is done.',
            'Cook the onions, garlic and tomatoes down into a sauce with the herbs.',
            'Fold everything together and let it sit for at least an hour. It is better warm than hot, and better still the next day.',
        ],
    },
    {
        title: 'French Onion Soup',
        time: 120,
        servings: 4,
        mealTypes: ['appetizer', 'dinner'],
        regions: ['western-european'],
        countries: ['France'],
        allergens: ['gluten', 'dairy'],
        diets: ['nut-free', 'egg-free'],
        calories: 410,
        nutrients: [
            { name: 'carbohydrates', amount: 38, unit: 'g' },
            { name: 'fat', amount: 20, unit: 'g' },
            { name: 'protein', amount: 18, unit: 'g' },
            { name: 'sodium', amount: 1250, unit: 'mg' },
        ],
        ingredients: [
            '1.5 kg onions, sliced thin',
            '60 g butter',
            '1.5 litres beef stock',
            '150 ml dry sherry',
            '1 baguette',
            '200 g gruyère',
            'Thyme and bay',
        ],
        instructions: [
            'Cook the onions in butter over a low heat for at least 45 minutes, stirring often, until they are deep brown and jammy.',
            'Deglaze with the sherry and scrape everything off the base of the pan.',
            'Add the stock and herbs and simmer gently for half an hour.',
            'Toast slices of baguette, float them on the filled bowls, and heap the gruyère on top.',
            'Grill until the cheese blisters and runs down the side.',
        ],
    },
    {
        title: 'Tortilla Española',
        time: 45,
        servings: 6,
        mealTypes: ['breakfast', 'brunch', 'appetizer'],
        regions: ['mediterranean', 'western-european'],
        countries: ['Spain'],
        allergens: ['eggs'],
        diets: ['vegetarian', 'gluten-free', 'dairy-free', 'nut-free', 'halal', 'kosher'],
        calories: 320,
        nutrients: [
            { name: 'protein', amount: 14, unit: 'g' },
            { name: 'fat', amount: 20, unit: 'g' },
            { name: 'carbohydrates', amount: 22, unit: 'g' },
        ],
        ingredients: [
            '800 g waxy potatoes, sliced thin',
            '2 onions, sliced',
            '6 eggs',
            '400 ml olive oil',
            'Salt',
        ],
        instructions: [
            'Poach the potatoes and onions gently in the oil at a low temperature until soft but not coloured, about 25 minutes.',
            'Drain them well, saving the oil for next time, and fold them into the beaten eggs. Let it sit for ten minutes.',
            'Cook in a small pan over a medium heat until the edges set and the middle still moves.',
            'Turn it out onto a plate and slide it back in to finish the other side.',
            'It should be barely set in the centre. Eat it warm, not hot.',
        ],
    },
    {
        title: 'Moussaka',
        time: 120,
        servings: 6,
        mealTypes: ['dinner'],
        regions: ['mediterranean'],
        countries: ['Greece'],
        allergens: ['dairy', 'eggs', 'gluten'],
        diets: ['nut-free'],
        calories: 580,
        nutrients: [
            { name: 'protein', amount: 30, unit: 'g' },
            { name: 'fat', amount: 36, unit: 'g' },
            { name: 'carbohydrates', amount: 28, unit: 'g' },
            { name: 'calcium', amount: 290, unit: 'mg' },
        ],
        ingredients: [
            '3 aubergines, sliced',
            '700 g lamb mince',
            '400 g tinned tomatoes',
            '1 tsp cinnamon',
            '80 g butter',
            '80 g flour',
            '800 ml milk',
            '2 egg yolks',
            '100 g kefalotyri',
        ],
        instructions: [
            'Salt the aubergine slices, leave them to drain, then roast or fry them until golden.',
            'Cook the lamb with onion, tomato and cinnamon until thick and almost dry.',
            'Make a béchamel, take it off the heat, and beat in the yolks and most of the cheese.',
            'Layer aubergine, meat, aubergine, then all the béchamel, and scatter the rest of the cheese over.',
            'Bake at 180°C for 45 minutes and rest it for twenty before cutting, or it will slump.',
        ],
    },
    {
        title: 'Greek Salad',
        time: 15,
        servings: 4,
        mealTypes: ['side', 'lunch'],
        regions: ['mediterranean'],
        countries: ['Greece'],
        allergens: ['dairy'],
        diets: ['vegetarian', 'gluten-free', 'egg-free', 'nut-free', 'halal', 'kosher', 'low-carb'],
        calories: 220,
        nutrients: [
            { name: 'fat', amount: 18, unit: 'g' },
            { name: 'protein', amount: 7, unit: 'g' },
            { name: 'carbohydrates', amount: 8, unit: 'g' },
            { name: 'calcium', amount: 160, unit: 'mg' },
        ],
        ingredients: [
            '4 ripe tomatoes, in wedges',
            '1 cucumber, thickly sliced',
            '1 red onion, sliced',
            '200 g feta, in one slab',
            'Handful kalamata olives',
            'Dried oregano',
            'Olive oil and red wine vinegar',
        ],
        instructions: [
            'Cut everything large. This is not a chopped salad.',
            'Layer the vegetables and olives in a shallow bowl and season them.',
            'Lay the feta on top whole, and never crumble it.',
            'Dress with plenty of oil, a little vinegar and a heavy pinch of oregano over the cheese.',
        ],
    },
    {
        title: 'Borscht',
        time: 90,
        servings: 6,
        mealTypes: ['lunch', 'dinner'],
        regions: ['eastern-european'],
        countries: ['Ukraine'],
        allergens: ['dairy'],
        diets: ['vegetarian', 'gluten-free', 'egg-free', 'nut-free'],
        calories: 240,
        nutrients: [
            { name: 'carbohydrates', amount: 32, unit: 'g' },
            { name: 'fibre', amount: 8, unit: 'g' },
            { name: 'fat', amount: 9, unit: 'g' },
            { name: 'folate', amount: 150, unit: 'µg' },
        ],
        ingredients: [
            '4 beetroot, grated',
            '2 carrots',
            '1 onion',
            '300 g white cabbage, shredded',
            '3 potatoes, cubed',
            '2 tbsp tomato purée',
            '1 tbsp red wine vinegar',
            '1.5 litres vegetable stock',
            'Soured cream and dill, to serve',
        ],
        instructions: [
            'Fry the onion and carrot, then add the grated beetroot, tomato purée and vinegar and cook for ten minutes.',
            'The vinegar is not optional — without an acid the beetroot fades from crimson to a dull brown.',
            'Add the stock, potatoes and cabbage and simmer until everything is tender.',
            'Let it stand off the heat for half an hour before serving.',
            'Serve with a spoonful of soured cream and a great deal of dill.',
        ],
    },
    {
        title: 'Hungarian Goulash',
        time: 150,
        servings: 6,
        mealTypes: ['lunch', 'dinner'],
        regions: ['eastern-european'],
        countries: ['Hungary'],
        allergens: [],
        diets: ['gluten-free', 'dairy-free', 'egg-free', 'nut-free', 'halal'],
        calories: 460,
        nutrients: [
            { name: 'protein', amount: 38, unit: 'g' },
            { name: 'fat', amount: 22, unit: 'g' },
            { name: 'carbohydrates', amount: 26, unit: 'g' },
            { name: 'iron', amount: 4.6, unit: 'mg' },
        ],
        ingredients: [
            '1 kg beef shin, cubed',
            '3 onions, chopped',
            '3 tbsp sweet Hungarian paprika',
            '2 red peppers',
            '3 potatoes',
            '2 tomatoes',
            '1 tsp caraway seed',
            '1.5 litres water',
        ],
        instructions: [
            'Cook the onions slowly in lard or oil until soft and golden.',
            'Take the pan off the heat before adding the paprika. Paprika burns in seconds and turns the whole pot bitter.',
            'Return it to a low heat, add the beef and caraway, and let it sweat in its own juices for twenty minutes.',
            'Add water to cover and simmer for two hours until the beef gives way.',
            'Add the peppers, potatoes and tomatoes for the last half hour.',
        ],
    },
    {
        title: 'Swedish Meatballs',
        time: 50,
        servings: 4,
        mealTypes: ['dinner'],
        regions: ['nordic'],
        countries: ['Sweden'],
        allergens: ['gluten', 'dairy', 'eggs'],
        diets: ['nut-free'],
        calories: 590,
        nutrients: [
            { name: 'protein', amount: 32, unit: 'g' },
            { name: 'fat', amount: 40, unit: 'g' },
            { name: 'carbohydrates', amount: 24, unit: 'g' },
        ],
        ingredients: [
            '400 g pork mince',
            '300 g beef mince',
            '80 g breadcrumbs soaked in milk',
            '1 egg',
            '1 onion, grated and softened',
            '1/4 tsp allspice',
            '300 ml beef stock',
            '150 ml double cream',
            'Lingonberry jam, to serve',
        ],
        instructions: [
            'Mix the meats with the soaked breadcrumbs, egg, onion and allspice, and work it until it is genuinely sticky.',
            'Roll small and fry in butter in batches, shaking the pan rather than turning them.',
            'Make a roux in the same pan, then whisk in the stock and cream and simmer until it coats a spoon.',
            'Return the meatballs to warm through.',
            'Serve with mashed potato, pickled cucumber and lingonberry.',
        ],
    },
    {
        title: 'Gravlax',
        time: 2880,
        servings: 10,
        mealTypes: ['appetizer', 'breakfast'],
        regions: ['nordic'],
        countries: ['Sweden', 'Norway'],
        allergens: ['fish'],
        diets: ['pescatarian', 'gluten-free', 'dairy-free', 'egg-free', 'nut-free', 'low-carb', 'keto', 'paleo'],
        calories: 180,
        nutrients: [
            { name: 'protein', amount: 20, unit: 'g' },
            { name: 'fat', amount: 11, unit: 'g' },
            { name: 'sodium', amount: 1400, unit: 'mg' },
            { name: 'vitamin-d', amount: 12, unit: 'µg' },
        ],
        ingredients: [
            '1 kg salmon fillet, skin on, pin-boned',
            '100 g coarse salt',
            '80 g sugar',
            '2 tbsp crushed white peppercorns',
            'Very large bunch dill',
            '2 tbsp aquavit (optional)',
        ],
        instructions: [
            'Mix the salt, sugar and pepper. Lay half the dill in a dish, the salmon on top, and pack the cure over it.',
            'Cover the fish with the rest of the dill, wrap tightly, and weigh it down with something heavy.',
            'Refrigerate for 48 hours, turning it twice a day and pouring off the brine that collects.',
            'Scrape the cure off, pat dry, and slice on a long diagonal as thinly as you can.',
            'Serve with mustard and dill sauce and rye bread.',
        ],
    },
    {
        title: 'Koshari',
        time: 75,
        servings: 6,
        mealTypes: ['lunch', 'dinner'],
        regions: ['north-african'],
        countries: ['Egypt'],
        allergens: ['gluten'],
        diets: ['vegan', 'vegetarian', 'dairy-free', 'egg-free', 'nut-free', 'halal', 'kosher'],
        calories: 520,
        nutrients: [
            { name: 'carbohydrates', amount: 92, unit: 'g' },
            { name: 'protein', amount: 18, unit: 'g' },
            { name: 'fibre', amount: 11, unit: 'g' },
            { name: 'iron', amount: 4.8, unit: 'mg' },
        ],
        ingredients: [
            '200 g brown lentils',
            '200 g rice',
            '150 g small macaroni',
            '4 onions, sliced very thin',
            '400 g tinned tomatoes',
            '2 tbsp white vinegar',
            '1 tsp cumin',
            '1 tin chickpeas',
            'Oil for frying',
        ],
        instructions: [
            'Fry the onions in plenty of oil, slowly, until they are deep brown and crisp. Drain them on a rack.',
            'Cook the lentils, then the rice with some of the onion oil, then the macaroni, keeping each separate.',
            'Simmer the tomatoes with garlic, cumin and vinegar into a sharp, thin sauce.',
            'Layer rice and lentils, then macaroni, then chickpeas.',
            'Flood with the tomato sauce and bury the whole thing under fried onions.',
        ],
    },
    {
        title: 'Doro Wat',
        time: 150,
        servings: 6,
        mealTypes: ['dinner'],
        regions: ['east-african'],
        countries: ['Ethiopia'],
        allergens: ['eggs', 'dairy'],
        diets: ['gluten-free', 'nut-free', 'halal'],
        calories: 480,
        nutrients: [
            { name: 'protein', amount: 40, unit: 'g' },
            { name: 'fat', amount: 28, unit: 'g' },
            { name: 'carbohydrates', amount: 18, unit: 'g' },
        ],
        ingredients: [
            '1.2 kg chicken drumsticks and thighs',
            '6 onions, very finely chopped',
            '4 tbsp berbere',
            '100 g niter kibbeh',
            '6 hard-boiled eggs',
            '2 tbsp ginger-garlic paste',
            '1 lemon',
        ],
        instructions: [
            'Cook the onions in a dry pan with no fat at all for 30 minutes, until they collapse and dry out.',
            'Only then add the niter kibbeh and the berbere, and cook another twenty minutes until it darkens.',
            'Add the chicken, rubbed first with lemon and salt, and turn it through the sauce.',
            'Simmer covered for an hour, adding water only when it threatens to catch.',
            'Score the boiled eggs and add them for the final fifteen minutes. Serve on injera.',
        ],
    },
    {
        title: 'Feijoada',
        time: 240,
        servings: 8,
        mealTypes: ['lunch'],
        regions: ['latin-american'],
        countries: ['Brazil'],
        allergens: [],
        diets: ['gluten-free', 'dairy-free', 'egg-free', 'nut-free'],
        calories: 680,
        nutrients: [
            { name: 'protein', amount: 42, unit: 'g' },
            { name: 'carbohydrates', amount: 48, unit: 'g' },
            { name: 'fat', amount: 34, unit: 'g' },
            { name: 'fibre', amount: 14, unit: 'g' },
        ],
        ingredients: [
            '500 g black beans, soaked overnight',
            '300 g smoked pork ribs',
            '200 g carne seca, soaked',
            '200 g linguiça',
            '150 g streaky bacon',
            '2 onions',
            '6 cloves garlic',
            '3 bay leaves',
            'Orange slices and farofa, to serve',
        ],
        instructions: [
            'Simmer the beans with the bay and the tougher cuts for two hours.',
            'Fry the sausage and bacon, then the onion and garlic, and add them to the pot.',
            'Cook for another hour and a half until the beans break down and the liquid goes thick and black.',
            'Crush a ladleful of beans and stir them back in to thicken it further.',
            'Serve with rice, sliced orange, farofa and sautéed greens.',
        ],
    },
    {
        title: 'Arepas',
        time: 30,
        servings: 4,
        mealTypes: ['breakfast', 'snack'],
        regions: ['latin-american'],
        countries: ['Venezuela', 'Colombia'],
        allergens: [],
        diets: ['vegan', 'vegetarian', 'gluten-free', 'dairy-free', 'egg-free', 'nut-free', 'halal', 'kosher'],
        calories: 260,
        ingredients: [
            '250 g masarepa (pre-cooked white maize flour)',
            '350 ml warm water',
            '1 tsp salt',
            'Oil for the pan',
        ],
        instructions: [
            'Stir the salt into the water, then rain in the masarepa with your hand, mixing as you go.',
            'Knead for two minutes and let it rest for five — the dough firms up considerably as it hydrates.',
            'Shape into discs about a centimetre and a half thick, smoothing any cracks at the edges with wet fingers.',
            'Griddle on both sides until a crust forms, then finish in the oven for fifteen minutes so they puff.',
            'Split and fill while hot.',
        ],
    },
    {
        title: 'New England Clam Chowder',
        time: 60,
        servings: 6,
        mealTypes: ['lunch', 'dinner'],
        regions: ['north-american'],
        countries: ['United States'],
        allergens: ['molluscs', 'dairy', 'gluten'],
        diets: ['pescatarian', 'nut-free', 'egg-free'],
        calories: 470,
        nutrients: [
            { name: 'protein', amount: 24, unit: 'g' },
            { name: 'fat', amount: 28, unit: 'g' },
            { name: 'carbohydrates', amount: 30, unit: 'g' },
            { name: 'iron', amount: 12, unit: 'mg' },
            { name: 'vitamin-b12', amount: 42, unit: 'µg' },
        ],
        ingredients: [
            '1.5 kg quahog or littleneck clams',
            '150 g salt pork, diced',
            '3 potatoes, cubed',
            '2 onions',
            '500 ml double cream',
            '2 tbsp flour',
            'Thyme and bay',
            'Oyster crackers',
        ],
        instructions: [
            'Steam the clams open in a little water, then strain and keep every drop of the liquor.',
            'Chop the clams. Render the salt pork and cook the onions in the fat.',
            'Stir in the flour, then the clam liquor, and add the potatoes and herbs.',
            'Simmer until the potatoes are tender, then add the cream and the chopped clams.',
            'Do not let it boil once the clams are back in, or they turn to rubber. Better still, make it a day ahead.',
        ],
    },
    {
        title: 'Pavlova',
        time: 180,
        servings: 8,
        mealTypes: ['dessert'],
        regions: ['oceanian'],
        countries: ['Australia', 'New Zealand'],
        allergens: ['eggs', 'dairy'],
        diets: ['vegetarian', 'gluten-free', 'nut-free', 'alcohol-free'],
        calories: 310,
        nutrients: [
            { name: 'sugars', amount: 42, unit: 'g' },
            { name: 'fat', amount: 12, unit: 'g' },
            { name: 'protein', amount: 4, unit: 'g' },
        ],
        ingredients: [
            '6 egg whites, at room temperature',
            '350 g caster sugar',
            '2 tsp cornflour',
            '1 tsp white wine vinegar',
            '500 ml double cream',
            'Passion fruit and berries',
        ],
        instructions: [
            'Whisk the whites to soft peaks, then add the sugar a spoonful at a time until the meringue is stiff and no longer grainy between your fingers.',
            'Fold in the cornflour and vinegar — these are what keep the middle marshmallowy.',
            'Shape into a circle with a slight hollow and bake at 120°C for 90 minutes.',
            'Turn the oven off and leave it inside, door shut, until completely cold. Cooling it fast is what cracks it.',
            'Top with softly whipped cream and fruit no more than an hour before serving.',
        ],
    },
    {
        title: 'Mango Lassi',
        time: 10,
        servings: 2,
        mealTypes: ['drink', 'snack'],
        regions: ['south-asian'],
        countries: ['India', 'Pakistan'],
        allergens: ['dairy'],
        diets: ['vegetarian', 'gluten-free', 'egg-free', 'nut-free', 'halal', 'kosher', 'alcohol-free'],
        calories: 220,
        nutrients: [
            { name: 'carbohydrates', amount: 38, unit: 'g' },
            { name: 'protein', amount: 8, unit: 'g' },
            { name: 'calcium', amount: 280, unit: 'mg' },
            { name: 'vitamin-c', amount: 36, unit: 'mg' },
        ],
        ingredients: [
            '2 ripe alphonso mangoes, or 300 g pulp',
            '300 g full-fat yoghurt',
            '100 ml cold milk',
            '2 tsp sugar, if needed',
            'Pinch ground cardamom',
        ],
        instructions: [
            'Blend the mango with the yoghurt until completely smooth.',
            'Loosen with milk to the thickness you want, and sweeten only if the fruit needs it.',
            'Add the cardamom and blend for a second more.',
            'Serve very cold, without ice, which only waters it down.',
        ],
    },
    {
        title: 'Egusi Soup',
        time: 75,
        servings: 6,
        mealTypes: ['lunch', 'dinner'],
        regions: ['west-african'],
        countries: ['Nigeria'],
        allergens: ['fish', 'shellfish'],
        diets: ['gluten-free', 'dairy-free', 'egg-free'],
        calories: 540,
        nutrients: [
            { name: 'protein', amount: 34, unit: 'g' },
            { name: 'fat', amount: 38, unit: 'g' },
            { name: 'carbohydrates', amount: 14, unit: 'g' },
        ],
        ingredients: [
            '300 g ground egusi (melon seed)',
            '500 g goat meat or beef',
            '200 g smoked fish',
            '2 tbsp ground crayfish',
            '300 g spinach or bitterleaf',
            '150 ml palm oil',
            '2 scotch bonnets',
            '1 onion',
        ],
        instructions: [
            'Boil the meat with onion, stock cube and pepper until tender, keeping the stock.',
            'Heat the palm oil, add the blended pepper and onion, and fry for ten minutes.',
            'Mix the egusi with a little water into a paste and drop it in in lumps. Leave it alone to set and fry, then break it up.',
            'Add the stock, smoked fish and crayfish and simmer for twenty minutes until the oil rises.',
            'Stir the greens through at the very end so they keep their colour.',
        ],
    },
    {
        title: 'Kung Pao Chicken',
        time: 30,
        servings: 4,
        mealTypes: ['lunch', 'dinner'],
        regions: ['east-asian'],
        countries: ['China'],
        allergens: ['peanuts', 'soy', 'gluten'],
        diets: ['dairy-free', 'egg-free'],
        calories: 460,
        nutrients: [
            { name: 'protein', amount: 34, unit: 'g' },
            { name: 'fat', amount: 24, unit: 'g' },
            { name: 'carbohydrates', amount: 22, unit: 'g' },
            { name: 'sodium', amount: 1180, unit: 'mg' },
        ],
        ingredients: [
            '600 g chicken thigh, cubed',
            '100 g roasted peanuts',
            '12 dried red chillies',
            '1 tbsp Sichuan peppercorns',
            '3 tbsp black vinegar',
            '2 tbsp soy sauce',
            '1 tbsp sugar',
            '2 tsp cornflour',
            '4 spring onions',
        ],
        instructions: [
            'Marinate the chicken in soy, wine and cornflour for twenty minutes.',
            'Mix the vinegar, soy, sugar and cornflour into a sauce and keep it beside the hob.',
            'Fry the chillies and peppercorns in oil until fragrant but not black, then push them aside.',
            'Sear the chicken hard without moving it, then stir-fry until cooked.',
            'Add the sauce, let it thicken in seconds, and throw in the peanuts and spring onion off the heat.',
        ],
    },
    {
        title: 'Pierogi Ruskie',
        time: 90,
        servings: 4,
        mealTypes: ['lunch', 'dinner'],
        regions: ['eastern-european'],
        countries: ['Poland'],
        allergens: ['gluten', 'dairy', 'eggs'],
        diets: ['vegetarian', 'nut-free'],
        calories: 450,
        nutrients: [
            { name: 'carbohydrates', amount: 62, unit: 'g' },
            { name: 'protein', amount: 14, unit: 'g' },
            { name: 'fat', amount: 16, unit: 'g' },
        ],
        ingredients: [
            '400 g plain flour',
            '1 egg',
            '200 ml warm water',
            '500 g potatoes, boiled',
            '250 g twaróg or farmer cheese',
            '2 onions',
            'Butter and soured cream, to serve',
        ],
        instructions: [
            'Make a soft dough with flour, egg, water and salt, and rest it under a cloth for half an hour.',
            'Mash the potato with the cheese and plenty of fried onion, and season it more heavily than seems right.',
            'Roll thin, cut discs, fill and seal with dry fingers — any filling on the edge will open in the water.',
            'Boil in batches until they float, then a further two minutes.',
            'Finish in butter with more fried onion, and serve with soured cream.',
        ],
    },
    {
        title: 'Beef Chili',
        time: 120,
        servings: 6,
        mealTypes: ['dinner', 'lunch'],
        regions: ['north-american'],
        countries: ['United States'],
        allergens: [],
        diets: ['gluten-free', 'dairy-free', 'egg-free', 'nut-free', 'halal'],
        calories: 520,
        nutrients: [
            { name: 'protein', amount: 36, unit: 'g' },
            { name: 'fat', amount: 28, unit: 'g' },
            { name: 'carbohydrates', amount: 30, unit: 'g' },
            { name: 'fibre', amount: 10, unit: 'g' },
        ],
        ingredients: [
            '1 kg beef chuck, cubed small',
            '4 ancho chillies',
            '2 chipotles in adobo',
            '2 onions',
            '400 g tinned tomatoes',
            '2 tins kidney beans',
            '1 tbsp cumin',
            '1 tbsp oregano',
            '250 ml dark beer',
        ],
        instructions: [
            'Toast and soak the anchos, then blend them with the chipotles into a paste.',
            'Brown the beef in batches, hard, and set it aside. Crowding the pan steams it and costs you the whole base of the dish.',
            'Cook the onions, add the chilli paste and spices, then deglaze with the beer.',
            'Return the beef with the tomatoes and simmer for ninety minutes.',
            'Add the beans for the last twenty. It is better the next day.',
        ],
    },
    {
        title: 'Overnight Oats with Berries',
        time: 5,
        servings: 1,
        mealTypes: ['breakfast'],
        regions: ['western-european', 'north-american'],
        countries: ['United Kingdom'],
        allergens: ['gluten', 'dairy'],
        diets: ['vegetarian', 'egg-free', 'nut-free', 'alcohol-free'],
        calories: 350,
        nutrients: [
            { name: 'carbohydrates', amount: 52, unit: 'g' },
            { name: 'protein', amount: 14, unit: 'g' },
            { name: 'fibre', amount: 7, unit: 'g' },
            { name: 'calcium', amount: 240, unit: 'mg' },
        ],
        ingredients: [
            '60 g rolled oats',
            '120 ml milk',
            '2 tbsp yoghurt',
            '1 tsp honey',
            'Handful of berries',
            'Pinch of salt',
        ],
        instructions: [
            'Stir the oats, milk, yoghurt, honey and salt together in a jar.',
            'Seal and refrigerate overnight.',
            'Top with berries in the morning.',
        ],
    },
    {
        title: 'Miso Soup',
        time: 15,
        servings: 4,
        mealTypes: ['breakfast', 'appetizer', 'side'],
        regions: ['east-asian'],
        countries: ['Japan'],
        allergens: ['soy', 'fish'],
        diets: ['pescatarian', 'dairy-free', 'egg-free', 'nut-free', 'low-carb'],
        calories: 80,
        nutrients: [
            { name: 'protein', amount: 6, unit: 'g' },
            { name: 'sodium', amount: 900, unit: 'mg' },
            { name: 'carbohydrates', amount: 6, unit: 'g' },
        ],
        ingredients: [
            '1 litre water',
            '10 g kombu',
            '20 g katsuobushi',
            '4 tbsp miso paste',
            '200 g silken tofu',
            '2 spring onions',
            'Wakame, rehydrated',
        ],
        instructions: [
            'Steep the kombu in cold water for half an hour, then heat it slowly and lift it out just before it boils.',
            'Add the katsuobushi, take it off the heat immediately, and strain after two minutes.',
            'Loosen the miso in a ladleful of the hot dashi before stirring it back in.',
            'Never boil the soup after the miso goes in — it flattens the flavour and turns it grainy.',
            'Add tofu, wakame and spring onion and serve at once.',
        ],
    },
    {
        title: 'Chocolate Chip Cookies',
        time: 40,
        servings: 24,
        mealTypes: ['dessert', 'snack'],
        regions: ['north-american'],
        countries: ['United States'],
        allergens: ['gluten', 'dairy', 'eggs', 'soy'],
        diets: ['vegetarian', 'alcohol-free'],
        calories: 210,
        nutrients: [
            { name: 'sugars', amount: 18, unit: 'g' },
            { name: 'fat', amount: 11, unit: 'g' },
            { name: 'carbohydrates', amount: 26, unit: 'g' },
        ],
        ingredients: [
            '225 g butter, browned and cooled',
            '200 g brown sugar',
            '100 g caster sugar',
            '2 eggs',
            '340 g plain flour',
            '1 tsp bicarbonate of soda',
            '300 g dark chocolate, chopped',
            'Flaky salt',
        ],
        instructions: [
            'Brown the butter until it smells of toffee and let it cool until it is thick again.',
            'Beat it with both sugars, then the eggs, until the mixture ribbons.',
            'Fold in the dry ingredients and the chocolate, chopped rather than chips so it runs in seams.',
            'Rest the dough in the fridge for 24 hours if you can. It makes more difference than any other step here.',
            'Bake at 180°C for 11 minutes — they should look underdone — and salt them as they come out.',
        ],
    },
    {
        title: 'Lemon & Herb Roast Chicken',
        time: 90,
        servings: 4,
        mealTypes: ['dinner', 'lunch'],
        regions: ['western-european'],
        countries: ['United Kingdom', 'France'],
        allergens: [],
        diets: ['gluten-free', 'dairy-free', 'egg-free', 'nut-free', 'halal', 'low-carb'],
        calories: 560,
        nutrients: [
            { name: 'protein', amount: 52, unit: 'g' },
            { name: 'fat', amount: 38, unit: 'g' },
            { name: 'carbohydrates', amount: 2, unit: 'g' },
        ],
        ingredients: [
            '1.6 kg whole chicken',
            '2 lemons',
            '4 sprigs thyme',
            '1 bulb garlic',
            '3 tbsp olive oil',
            'Flaky salt and black pepper',
        ],
        instructions: [
            'Heat the oven to 200°C fan.',
            'Halve one lemon and push it into the cavity with the thyme and the garlic bulb, cut across the middle.',
            'Rub the skin with oil, the juice of the second lemon, salt and plenty of pepper.',
            'Roast for 70 minutes, basting once at the halfway mark.',
            'Rest for 15 minutes before carving — this is not optional.',
        ],
    },
    {
        title: 'Zaalouk',
        time: 45,
        servings: 4,
        mealTypes: ['side', 'appetizer'],
        regions: ['north-african'],
        countries: ['Morocco'],
        allergens: [],
        diets: ['vegan', 'vegetarian', 'gluten-free', 'dairy-free', 'egg-free', 'nut-free', 'halal', 'kosher', 'low-carb'],
        calories: 140,
        ingredients: [
            '2 aubergines',
            '4 tomatoes, grated',
            '4 cloves garlic',
            '1 tsp cumin',
            '1 tsp paprika',
            'Small bunch coriander',
            '4 tbsp olive oil',
            '1 lemon',
        ],
        instructions: [
            'Char the aubergines whole over a flame or under a grill until the skins blacken and they collapse.',
            'Scrape out the flesh and chop it roughly.',
            'Cook the grated tomato with the garlic and spices until it thickens.',
            'Add the aubergine and cook it down together, mashing as you go, for twenty minutes.',
            'Finish with lemon, coriander and a good deal more olive oil than feels reasonable.',
        ],
    },
    {
        title: 'Congee with Ginger and Spring Onion',
        time: 90,
        servings: 4,
        mealTypes: ['breakfast', 'lunch'],
        regions: ['east-asian'],
        countries: ['China'],
        allergens: ['soy'],
        diets: ['vegan', 'vegetarian', 'dairy-free', 'egg-free', 'nut-free', 'halal', 'kosher'],
        calories: 210,
        nutrients: [
            { name: 'carbohydrates', amount: 44, unit: 'g' },
            { name: 'protein', amount: 5, unit: 'g' },
            { name: 'sodium', amount: 520, unit: 'mg' },
        ],
        ingredients: [
            '150 g jasmine rice',
            '2 litres vegetable stock',
            'Large thumb of ginger, sliced',
            '4 spring onions',
            '2 tbsp soy sauce',
            '1 tbsp sesame oil',
            'White pepper',
        ],
        instructions: [
            'Rinse the rice and freeze it for an hour if you have the time — the grains burst faster from frozen.',
            'Simmer rice, stock and ginger very gently for at least an hour, stirring now and then.',
            'It is ready when no individual grains are left and it falls off the spoon in a sheet.',
            'Season with soy, sesame oil and a lot of white pepper.',
            'Top with spring onion and whatever else is around.',
        ],
    },
    {
        title: 'Caprese Salad',
        time: 10,
        servings: 2,
        mealTypes: ['appetizer', 'side', 'lunch'],
        regions: ['mediterranean'],
        countries: ['Italy'],
        allergens: ['dairy'],
        diets: ['vegetarian', 'gluten-free', 'egg-free', 'nut-free', 'halal', 'kosher', 'low-carb', 'keto'],
        calories: 280,
        nutrients: [
            { name: 'fat', amount: 22, unit: 'g' },
            { name: 'protein', amount: 16, unit: 'g' },
            { name: 'carbohydrates', amount: 6, unit: 'g' },
            { name: 'calcium', amount: 380, unit: 'mg' },
        ],
        ingredients: [
            '300 g buffalo mozzarella',
            '3 very ripe tomatoes',
            'Large handful basil',
            'Best olive oil you own',
            'Flaky salt',
        ],
        instructions: [
            'Take the mozzarella out of the fridge half an hour beforehand. Cold mozzarella tastes of nothing.',
            'Slice the tomatoes thickly and salt them on a plate for five minutes.',
            'Tear the mozzarella rather than slicing it, so the oil catches in the rough edges.',
            'Layer with basil, salt again, and pour the oil over generously. No vinegar, ever.',
        ],
    },
    {
        title: 'Masala Chai',
        time: 15,
        servings: 2,
        mealTypes: ['drink', 'breakfast'],
        regions: ['south-asian'],
        countries: ['India', 'Pakistan'],
        allergens: ['dairy'],
        diets: ['vegetarian', 'gluten-free', 'egg-free', 'nut-free', 'halal', 'kosher', 'alcohol-free'],
        calories: 120,
        ingredients: [
            '300 ml water',
            '200 ml whole milk',
            '2 tsp strong Assam tea',
            '4 green cardamom pods, crushed',
            '1 small piece cinnamon',
            '2 cloves',
            'Thin slice ginger',
            'Sugar to taste',
        ],
        instructions: [
            'Crush the spices roughly and boil them in the water for five minutes to draw them out.',
            'Add the tea and boil for two minutes more.',
            'Add the milk and sugar and bring it up to the boil three times, pulling the pan off each time it rises.',
            'Strain into cups from a height.',
        ],
    },
    {
        title: 'Roasted Cauliflower Steaks',
        time: 40,
        servings: 2,
        mealTypes: ['dinner', 'side'],
        regions: ['western-european', 'middle-eastern'],
        countries: ['United Kingdom'],
        allergens: ['sesame'],
        diets: ['vegan', 'vegetarian', 'gluten-free', 'dairy-free', 'egg-free', 'nut-free', 'halal', 'kosher', 'low-carb'],
        calories: 240,
        nutrients: [
            { name: 'fibre', amount: 8, unit: 'g' },
            { name: 'fat', amount: 16, unit: 'g' },
            { name: 'carbohydrates', amount: 14, unit: 'g' },
            { name: 'vitamin-c', amount: 92, unit: 'mg' },
        ],
        ingredients: [
            '1 large cauliflower',
            '3 tbsp olive oil',
            '2 tsp ras el hanout',
            '3 tbsp tahini',
            '1 lemon',
            'Pomegranate seeds',
            'Parsley',
        ],
        instructions: [
            'Cut the cauliflower down through the stem into thick slabs. Keep the core — it holds each steak together.',
            'Oil and spice them heavily and roast at 220°C for 25 minutes, turning once.',
            'Loosen the tahini with lemon and cold water until it goes from seized to pourable.',
            'Spoon the tahini over and finish with pomegranate and parsley.',
        ],
    },
    {
        title: 'Shrimp and Grits',
        time: 45,
        servings: 4,
        mealTypes: ['brunch', 'dinner'],
        regions: ['north-american'],
        countries: ['United States'],
        allergens: ['shellfish', 'dairy'],
        diets: ['pescatarian', 'gluten-free', 'egg-free', 'nut-free'],
        calories: 610,
        nutrients: [
            { name: 'protein', amount: 34, unit: 'g' },
            { name: 'fat', amount: 32, unit: 'g' },
            { name: 'carbohydrates', amount: 44, unit: 'g' },
        ],
        ingredients: [
            '200 g stone-ground grits',
            '600 ml whole milk',
            '600 ml water',
            '100 g sharp cheddar',
            '500 g prawns',
            '4 rashers streaky bacon',
            '2 spring onions',
            '1 lemon',
        ],
        instructions: [
            'Cook the grits in milk and water over the lowest heat for 40 minutes, whisking often. Quick grits are not a substitute.',
            'Beat in butter and cheese at the end.',
            'Crisp the bacon, then cook the prawns in the fat for ninety seconds a side.',
            'Deglaze with lemon and a splash of stock.',
            'Spoon the prawns and their pan juices over the grits, with the bacon and spring onion on top.',
        ],
    },
    {
        title: 'Fattoush',
        time: 20,
        servings: 4,
        mealTypes: ['side', 'lunch', 'appetizer'],
        regions: ['levantine'],
        countries: ['Lebanon', 'Syria'],
        allergens: ['gluten'],
        diets: ['vegan', 'vegetarian', 'dairy-free', 'egg-free', 'nut-free', 'halal', 'kosher'],
        calories: 230,
        ingredients: [
            '2 stale flatbreads',
            '3 tomatoes',
            '1 cucumber',
            '4 radishes',
            '1 romaine lettuce',
            'Large bunch parsley and mint',
            '2 tbsp sumac',
            '1 tbsp pomegranate molasses',
            'Olive oil and lemon',
        ],
        instructions: [
            'Tear the bread and fry or bake it until properly crisp, then salt it while hot.',
            'Chop the vegetables into rough, generous pieces.',
            'Whisk the lemon, pomegranate molasses, sumac and oil into a sharp dressing.',
            'Add the bread at the last possible moment. It should still crackle when it reaches the table.',
        ],
    },
    {
        title: 'Chicken Adobo',
        time: 60,
        servings: 4,
        mealTypes: ['lunch', 'dinner'],
        regions: ['southeast-asian'],
        countries: ['Philippines'],
        allergens: ['soy', 'gluten'],
        diets: ['dairy-free', 'egg-free', 'nut-free', 'halal'],
        calories: 490,
        nutrients: [
            { name: 'protein', amount: 40, unit: 'g' },
            { name: 'fat', amount: 30, unit: 'g' },
            { name: 'sodium', amount: 1600, unit: 'mg' },
        ],
        ingredients: [
            '1 kg chicken thighs and drumsticks',
            '120 ml soy sauce',
            '120 ml cane vinegar',
            '1 head garlic, crushed',
            '3 bay leaves',
            '1 tbsp whole black peppercorns',
            '250 ml water',
        ],
        instructions: [
            'Marinate the chicken in the soy, garlic and pepper for an hour.',
            'Bring everything to a simmer and add the vinegar without stirring. Let it cook off for two minutes before you touch it, or it stays harsh.',
            'Simmer covered for 30 minutes, turning the pieces once.',
            'Lift the chicken out and reduce the sauce until it turns syrupy.',
            'Fry the chicken briefly in the reduced sauce to glaze it, and serve with a great deal of rice.',
        ],
    },
    {
        title: 'Banana Bread',
        time: 80,
        servings: 10,
        mealTypes: ['breakfast', 'snack', 'dessert'],
        regions: ['north-american'],
        countries: ['United States'],
        allergens: ['gluten', 'eggs', 'dairy', 'tree-nuts'],
        diets: ['vegetarian', 'alcohol-free'],
        calories: 290,
        nutrients: [
            { name: 'carbohydrates', amount: 42, unit: 'g' },
            { name: 'fat', amount: 12, unit: 'g' },
            { name: 'sugars', amount: 22, unit: 'g' },
            { name: 'potassium', amount: 210, unit: 'mg' },
        ],
        ingredients: [
            '4 very black bananas',
            '150 g butter, melted',
            '180 g brown sugar',
            '2 eggs',
            '260 g plain flour',
            '1 tsp bicarbonate of soda',
            '1 tsp cinnamon',
            '100 g walnuts',
        ],
        instructions: [
            'Use bananas that look ruined. Yellow ones make a bland, dry loaf.',
            'Mash them thoroughly and beat in the butter, sugar and eggs.',
            'Fold in the dry ingredients until just combined, then the walnuts.',
            'Bake at 170°C for about an hour, covering the top with foil if it darkens early.',
            'Cool it completely in the tin before slicing.',
        ],
    },
];
